language: csharp
dotnet: 3.1.100
mono: latest
sudo: false
dist: bionic
env:
  - PATH=$PATH:/home/travis/.dotnet/tools
script:
  - dotnet tool install paket -g
  - dotnet tool install fake-cli -g
  - paket restore
  - fake run build.fsx -e "DisableNet40=true" target RunTests
