language: csharp
dotnet: 2.1.402
mono: latest
sudo: false
dist: trusty
env:
  - PATH=$PATH:/home/travis/.dotnet/tools
script:
  - mono ./.paket/paket.exe restore
  - dotnet tool install fake-cli -g
  - fake run build.fsx target RunTests
