image: Visual Studio 2019
version: "{build}"
branches:
  only:
    - master
init:
  - git config --global core.autocrlf true
  - dotnet tool install paket -g
  - dotnet tool install fake-cli -g
build: off
before_test:
  - paket restore
test_script:
  - fake run build.fsx target RunTests
