image: Visual Studio 2017
version: "{build}"
init:
  - git config --global core.autocrlf true
  - dotnet tool install fake-cli -g
build: off
before_test:
  - .\.paket\paket.exe restore
test_script:
  - fake run build.fsx target RunTests
