image: Visual Studio 2019
version: "{build}"
branches:
  only:
    - master
init:
  - ps: appveyor DownloadFile https://download.visualstudio.microsoft.com/download/pr/639f7cfa-84f8-48e8-b6c9-82634314e28f/8eb04e1b5f34df0c840c1bffa363c101/dotnet-sdk-3.1.100-win-x64.exe -FileName "C:\dotnet.exe"
  - cmd: call C:\dotnet.exe /install /quiet /norestart
  - dotnet --info
  - git config --global core.autocrlf true
  - dotnet tool install paket -g
  - dotnet tool install fake-cli -g
build: off
before_test:
  - paket restore
test_script:
  - fake run build.fsx -e "DisableNet40=true" target RunTests
