image: Visual Studio 2017
version: "{build}"
branches:
  only:
    - master
init:
  - git config --global core.autocrlf true
  - %APPVEYOR_BUILD_FOLDER%\.paket\paket.exe restore
  - dotnet tool install fake-cli -g
build: off
test_script:
  - fake run build.fsx target RunTests
